name: CI - Testes Automatizados

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

  schedule:
    - cron: '15 00 * * *'

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 22

      # Sistema Login

      - name: Instalar dependências - Login
        working-directory: 03-programacao-para-automacao/sistema-login
        run: npm install

      - name: Executar testes - Login
        working-directory: 03-programacao-para-automacao/sistema-login
        run: npm test

      # Sistema Pagamentos

      - name: Instalar dependências - Pagamentos
        working-directory: 03-programacao-para-automacao/sistema-pagamentos
        run: npm install

      - name: Executar testes - Pagamentos
        working-directory: 03-programacao-para-automacao/sistema-pagamentos
        run: npm test
    
      - name: Upload relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: |
            03-programacao-para-automacao/sistema-login/reports
            03-programacao-para-automacao/sistema-pagamentos/reports
        
      - name: Gerar relatório HTML - Login
        working-directory: 03-programacao-para-automacao/sistema-login
        run: npm run test:html

      - name: Gerar relatório HTML - Pagamentos
        working-directory: 03-programacao-para-automacao/sistema-pagamentos
        run: npm run test:html

      - name: Upload relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: |
            03-programacao-para-automacao/sistema-login/reports
            03-programacao-para-automacao/sistema-login/mochawesome-report
            03-programacao-para-automacao/sistema-pagamentos/reports
            03-programacao-para-automacao/sistema-pagamentos/mochawesome-report